
package com.woody.framework.ws.cxfspring.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWorldWs", targetNamespace = "http://server.cxfspring.ws.framework.woody.com/", wsdlLocation = "http://localhost:8080/woody-ding/myService/fkjava?WSDL")
public class HelloWorldWs
    extends Service
{

    private final static URL HELLOWORLDWS_WSDL_LOCATION;
    private final static WebServiceException HELLOWORLDWS_EXCEPTION;
    private final static QName HELLOWORLDWS_QNAME = new QName("http://server.cxfspring.ws.framework.woody.com/", "HelloWorldWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/woody-ding/myService/fkjava?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWORLDWS_WSDL_LOCATION = url;
        HELLOWORLDWS_EXCEPTION = e;
    }

    public HelloWorldWs() {
        super(__getWsdlLocation(), HELLOWORLDWS_QNAME);
    }

    public HelloWorldWs(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWORLDWS_QNAME, features);
    }

    public HelloWorldWs(URL wsdlLocation) {
        super(wsdlLocation, HELLOWORLDWS_QNAME);
    }

    public HelloWorldWs(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWORLDWS_QNAME, features);
    }

    public HelloWorldWs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldWs(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWebService
     */
    @WebEndpoint(name = "HelloWebServiceImplPort")
    public HelloWebService getHelloWebServiceImplPort() {
        return super.getPort(new QName("http://server.cxfspring.ws.framework.woody.com/", "HelloWebServiceImplPort"), HelloWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWebService
     */
    @WebEndpoint(name = "HelloWebServiceImplPort")
    public HelloWebService getHelloWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.cxfspring.ws.framework.woody.com/", "HelloWebServiceImplPort"), HelloWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWORLDWS_EXCEPTION!= null) {
            throw HELLOWORLDWS_EXCEPTION;
        }
        return HELLOWORLDWS_WSDL_LOCATION;
    }

}
